config/routes.rb
Rails.application.routes.draw do

  resources :recommendations
  post '/rate' => 'rater#create', :as => 'rate'
  resources :comments
  resources :students_posts
  put '/students_posts/:id/internship', to: 'students_posts#internship'
  put '/students_posts/:id/choose', to: 'students_posts#choose', :as => 'choose'

  resources :tags, only: [:index, :show]
  put '/bossy/interview_select', to: 'students_posts#interview_select'
  get '/home', to: 'homes#index'

  constraints subdomain: 'teacher' do
    namespace :teacher do
      resources :teachers
      # get '/teachers/request', to: 'teachers#request'
      # get '/students/status', to: 'students#status'
      # resources :students
      # resources :companies
      # resources :recommendations
      resources :recommendations
      resources :students
      resources :posts
    end
    devise_for :teachers, path: 'teachers', controller: { sessions: "teachers/sessions"}
  end


  constraints subdomain: 'admin' do
    namespace :admin do
      resources :admins
      get '/students/status', to: 'students#status'
      resources :students
      resources :companies
      resources :recommendations
      resources :posts
    end
    devise_for :admins, path: 'admins', controller: { sessions: "admins/sessions"}
  end

  constraints subdomain: 'student' do
    # devise_for :students, path: 'students', controller: { sessions: "students/sessions"}
    namespace :student do
      get '/companies/:id', to: 'companies#show'
      get '/students/status', to: 'students#status'
      resources :students
      resources :posts, only: [:index, :show]

    end
    devise_for :students, path: 'students', controller: { sessions: "students/sessions"}
  end

  constraints subdomain: 'company' do


    namespace :company do
      get '/students/:id', to: 'students#show'
      resources :companies
      resources :posts
      put '/students/:id/requesting', to: 'students#requesting' ,as: "student_requesting"
      put '/posts/:id/close', to: 'posts#close' ,as: "post_close"
      put '/posts/:id/complete', to: 'posts#complete' ,as: "post_complete"
      get '/completed', to: 'companies#completed'
      put '/students_posts/:id/interview', to: 'students_posts#interview'
      put '/students_posts/interview_select', to: 'students_posts#interview_select'
      put '/students_posts/internship_select', to: 'students_posts#internship_select'
      put '/students_posts/:id/internship', to: 'students_posts#internship'

    end
    devise_for :companies, path: 'companies', controller: { companies: "companies/sessions"}
  end
  # devise_for :students
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :student

  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :recommendations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/recommendations_controller.rb
class Admin::RecommendationsController < Admin::AppController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]

  # GET /recommendations
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1
  def show
    @post = Student.find(params[:id])
    @recommendation = Recommendation.new( :student_id => @student )
  end

  # GET /recommendations/new
  def new
    session[:view_student] = params[:view_student]
    session[:current_user] = params[:current_user]
    @admin = Admin.find(session[:current_user])
    @student = Student.find(session[:view_student])
    @recommendation = Recommendation.new
  end

  # GET /recommendations/1/edit
  def edit
  end

  # POST /recommendations
  def create
    @student = Student.find(session[:view_student])
    @admin = Admin.find(session[:current_user])
    @recommendation = Recommendation.new(recommendation_params)
    @recommendation.student_id = session[:view_student]
    @recommendation.admin_id = session[:current_user]

    if @recommendation.save
      flash[:success] = 'Recommendation was successfully created.'
      redirect_to admin_student_path(@student)
    else
      render :new
    end
  end

  # PATCH/PUT /recommendations/1
  def update
    if @recommendation.update(recommendation_params)
      flash[:warning] = 'Recommendation was successfully updated.'
      redirect_to @recommendation
    else
      render :edit
    end
  end

  # DELETE /recommendations/1
  def destroy
    @recommendation.destroy
    flash[:danger] = 'Recommendation was successfully destroyed.'
    redirect_to admin_recommendations_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recommendation_params
      params.require(:recommendation).permit(:title, :body, :student_id, :admin_id, :teacher_id)
    end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  # GET /recommendations
  def index
    @recommendations = Recommendation.all
  end
end

app/controllers/teacher/app_controller.rb
class Teacher::AppController < ApplicationController
  before_action :authenticate_teacher!


end

app/controllers/teacher/recommendations_controller.rb
class Teacher::RecommendationsController < Teacher::AppController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]

  # GET /recommendations
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1
  def show
    @post = Student.find(params[:id])
    @recommendation = Recommendation.new( :student_id => @student )
  end

  # GET /recommendations/new
  def new
    session[:view_student] = params[:view_student]
    session[:current_user] = params[:current_user]
    @teacher = Teacher.find(session[:current_user])
    @student = Student.find(session[:view_student])
    @recommendation = Recommendation.new
  end

  # GET /recommendations/1/edit
  def edit
  end

  # POST /recommendations
  def create
    @student = Student.find(session[:view_student])
    @teacher = Teacher.find(session[:current_user])
    @recommendation = Recommendation.new(recommendation_params)
    @recommendation.student_id = session[:view_student]
    @recommendation.teacher_id = session[:current_user]

    if @recommendation.save
      flash[:success] = 'Recommendation was successfully created.'
      @student.to_filled!
      redirect_to teacher_teachers_path
    else
      render :new
    end
  end

  # PATCH/PUT /recommendations/1
  def update
    if @recommendation.update(recommendation_params)
      flash[:warning] = 'Recommendation was successfully updated.'
      redirect_to @recommendation
    else
      render :edit
    end
  end

  # DELETE /recommendations/1
  def destroy
    @recommendation.destroy
    flash[:danger] = 'Recommendation was successfully destroyed.'
    redirect_to admin_recommendations_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recommendation_params
      params.require(:recommendation).permit(:title, :body, :student_id, :admin_id, :teacher_id)
    end
end

app/controllers/teacher/students_controller.rb
class Teacher::StudentsController < Teacher::AppController
  before_action :set_student, only: [:request]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

end

app/controllers/teacher/teachers_controller.rb
class Teacher::TeachersController < Teacher::AppController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to @teacher, notice: 'Teacher was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /teachers/1
  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher, notice: 'Teacher was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /teachers/1
  def destroy
    @teacher.destroy
    redirect_to teachers_url, notice: 'Teacher was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def teacher_params
      params.require(:teacher).permit(:name, :age, :interest, :major, :minor)
    end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teacher/recommendations/_form.html.erb
<%= form_for(recommendation , :url => url_for(:controller => locals[:controller], :action => locals[:action])) do |form| %>

  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% @recommendation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :recommendation_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :recommendation_body %>
  </div>

  <!-- <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id, id: :recommendation_student_id %>
  </div>

  <div class="field">
    <%= form.label :admin_id %>
    <%= form.text_field :admin_id, id: :recommendation_admin_id %>
  </div> -->
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teacher/recommendations/edit.html.erb
<h1>Editing Recommendation</h1>

<%= render 'form', recommendation: @recommendation %>

<%= link_to 'Show', @recommendation %> |
<%= link_to 'Back', recommendations_path %>

app/views/teacher/recommendations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recommendations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Student</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommendations.each do |recommendation| %>
      <tr>
        <td><%= recommendation.title %></td>
        <td><%= recommendation.body %></td>
        <td><%= recommendation.student %></td>
        <td><%= recommendation.admin %></td>
        <td><%= link_to 'Show', recommendation %></td>
        <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
        <td><%= link_to 'Destroy', admin_recommendation_path(id: recommendation.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recommendation', new_recommendation_path %>

app/views/teacher/recommendations/new.html.erb
<h1>New Recommendation</h1>

<%= render 'form', recommendation: [:recommendation, @recommendation],
:locals => {:controller => 'recommendations', :action => 'create'} %>

<%= link_to 'Back', admin_recommendations_path %>

app/views/teacher/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recommendation.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @recommendation.body %>
</p>

<p>
  <strong>Student:</strong>
  <%= @recommendation.student %>
</p>

<p>
  <strong>Company:</strong>
  <%= @recommendation.company %>
</p>

<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back', recommendations_path %>