config/routes.rb
Rails.application.routes.draw do

  resources :recommendations
  post '/rate' => 'rater#create', :as => 'rate'
  resources :comments
  resources :students_posts
  put '/students_posts/:id/internship', to: 'students_posts#internship'
  put '/students_posts/:id/choose', to: 'students_posts#choose', :as => 'choose'

  resources :tags, only: [:index, :show]
  put '/bossy/interview_select', to: 'students_posts#interview_select'
  get '/home', to: 'homes#index'

  constraints subdomain: 'teacher' do
    namespace :teacher do
      resources :teachers
      # get '/teachers/request', to: 'teachers#request'
      # get '/students/status', to: 'students#status'
      # resources :students
      # resources :companies
      # resources :recommendations
      resources :recommendations
      resources :students
      resources :posts
    end
    devise_for :teachers, path: 'teachers', controller: { sessions: "teachers/sessions"}
  end


  constraints subdomain: 'admin' do
    namespace :admin do
      resources :admins
      get '/students/status', to: 'students#status'
      resources :students
      resources :companies
      resources :recommendations
      resources :posts
    end
    devise_for :admins, path: 'admins', controller: { sessions: "admins/sessions"}
  end

  constraints subdomain: 'student' do
    # devise_for :students, path: 'students', controller: { sessions: "students/sessions"}
    namespace :student do
      get '/companies/:id', to: 'companies#show'
      get '/students/status', to: 'students#status'
      resources :students
      resources :posts, only: [:index, :show]

    end
    devise_for :students, path: 'students', controller: { sessions: "students/sessions"}
  end

  constraints subdomain: 'company' do


    namespace :company do
      get '/students/:id', to: 'students#show'
      resources :companies
      resources :posts
      put '/students/:id/requesting', to: 'students#requesting' ,as: "student_requesting"
      put '/posts/:id/close', to: 'posts#close' ,as: "post_close"
      put '/posts/:id/complete', to: 'posts#complete' ,as: "post_complete"
      get '/completed', to: 'companies#completed'
      put '/students_posts/:id/interview', to: 'students_posts#interview'
      put '/students_posts/interview_select', to: 'students_posts#interview_select'
      put '/students_posts/internship_select', to: 'students_posts#internship_select'
      put '/students_posts/:id/internship', to: 'students_posts#internship'

    end
    devise_for :companies, path: 'companies', controller: { companies: "companies/sessions"}
  end
  # devise_for :students
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  include AASM
  has_many :students_posts
  has_many :recommendations
  has_many :comments, :dependent => :destroy
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://via.placeholder.com/150x150"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ActsAsTaggableOn.delimiter = [',', ' ']
  ratyrate_rater
  ratyrate_rateable "score"
  acts_as_taggable_on :skills


  aasm :column => 'state' do # default column: aasm_state
    state :no_request, :initial => true
    state :requested

    event :to_requested do
      transitions :from => :no_request, :to => :requested
    end

    event :to_filled do
      transitions :from => :requested, :to => :no_request
    end

  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::AppController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # GET /students/status
  def status
    @student = Student.find(params[:id])
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to [:student, @student], notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /students/1
  def update
    student_params[:password] = @student.password
    if @student.update(student_params)
      redirect_to [:admin, @student], notice: 'Student was successfully updated.'
    else
      render :edit
    end
    # if current_student.update_with_password(params[:password])
    #   sign_in(current_student, :bypass => true)
    #   flash[:notice] = 'Password updated.'
    #   redirect_to account_path
    # else
    #   render :action => :show
    # end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    redirect_to student_students_url, notice: 'Student was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:name, :age, :occupation, :email, :skill_list)
    end
end

app/controllers/company/students_controller.rb
class Company::StudentsController < Company::AppController
  before_action :set_student, only: [:show, :requesting]

  # GET /students/1
  def show
  end

  def requesting
    if @student.no_request?
      @student.to_requested!
      redirect_to company_path(@student.id)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

end

app/controllers/student/app_controller.rb
class Student::AppController < ApplicationController
  before_action :authenticate_student!, except: [:show]
end

app/controllers/student/companies_controller.rb
class Student::CompaniesController < Student::AppController
  before_action :set_company, only: [:show]


  # GET /companies/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

end

app/controllers/student/posts_controller.rb
class Student::PostsController < Student::AppController
  require 'will_paginate/array'
  before_action :set_post, only: [:show]
  has_scope :starts_with, :has_tag, :is_opened, :is_published

  def index
      @posts = apply_scopes(Post.all).paginate(:page => params[:page], :per_page => 5)
      @posts = apply_scopes(@posts).is_opened
      @posts = apply_scopes(@posts).is_published
  end

  # GET /posts/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :state, :jobDescription, :salary,
                                    :skillRequirement, :location, :company_id,
                                     :tag_list)
    end
end

app/controllers/student/students_controller.rb
class Student::StudentsController < Student::AppController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :status]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # GET /students/status
  def status
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    if @student.save
      flash[:success] =  'Student was successfully created.'
      redirect_to [:student, @student]
    else
      render :new
    end
  end

  # PATCH/PUT /students/1
  def update
    student_params[:password] = current_student.password
    if @student.update(student_params)
      flash[:warning] = 'Student was successfully updated.'
      redirect_to [:student, @student]
    else
      render :edit
    end
    # if current_student.update_with_password(params[:password])
    #   sign_in(current_student, :bypass => true)
    #   flash[:notice] = 'Password updated.'
    #   redirect_to account_path
    # else
    #   render :action => :show
    # end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    flash[:danger] = 'Student was successfully destroyed.'
    redirect_to student_students_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:name, :age, :occupation, :email, :skill_list,:avatar)
    end

end

app/controllers/students/confirmations_controller.rb
class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
   layout "public"

  # GET /resource/sign_in
  # def new
  #   super
  #   raise resource
  # end

  # POST /resource/sign_in
  # def create
  #   super
  #   raise resource
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teacher/students_controller.rb
class Teacher::StudentsController < Teacher::AppController
  before_action :set_student, only: [:request]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/student/students/_comment.html.erb
<div class="well">
  <h2><%= comment.name %></h2>
  <p class="text-muted">Added by <strong><%= comment.company.name %></strong> on
    <%= l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %></p>
    <%= rating_for_user @student, comment.company, "score", readonly: true %>
  <blockquote>
    <p><%= comment.body %></p>
  </blockquote>
</div>

app/views/student/students/_form.html.erb
<%= form_for(student , local: true, html: { multipart: true }) do |form| %>

<% if @student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

    <ul>
    <% @student.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :student_age %>
  </div>

  <div class="field">
    <%= form.label :occupation %>
    <%= form.text_field :occupation, id: :student_occupation %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :student_email %>
  </div>

  <div class="field">
    <%= form.label :skill_list %>
    <%= form.text_field :skill_list, id: :student_skill_list %>
  </div>

  <%= form.file_field :avatar %>
  <!-- <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :student_password %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student/students/_recommendation.html.erb
<div class="well">
  <h2><%= recommendation.title %></h2>
  <p class="text-muted">Added by <strong><%= recommendation.admin.email %></strong> on
    <%= l(recommendation.created_at, format: '%B, %d %Y %H:%M:%S') %></p>
  <blockquote>
    <p><%= recommendation.body %></p>
  </blockquote>
</div>

app/views/student/students/_statusRow.html.erb
<%= stylesheet_link_tag 'row_stylesheets' %>
<div class="row row-margin-bottom">
  <div class="col-md-12 no-padding lib-item" data-category="view">
     <div class="lib-panel">
         <div class="row box-shadow">
             <div class="col-md-3">
                 <img class="lib-img-show" src="http://placehold.it/100x100">
             </div>
             <div class="col-md-9">
                 <div class="lib-row lib-header">
                     <h3><%= link_to post.title, student_post_path(:id => post.id) %></h3>
                     <div class="lib-header-seperator"></div>
                     Status: <%= status %>
                 </div>
                 <div class="lib-row lib-desc">
                    <p>
                    <%= truncate("(More than 300 will be truncate)", length:300) %>
                    </p>
                 </div>
             </div>
         </div>
     </div>
  </div>
</div>

app/views/student/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: [:student, @student] %>

<%= link_to 'Show', student_student_path(id: @student.id) %> |
<%= link_to 'Back', student_students_path %>

app/views/student/students/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'layouts/title', :title => "Dashboard" %>
<div class="col-md-8">
  <h1>Students</h1>

  <table>
    <thead>
      <tr>
        <div>Signed in as... <%= current_student.email %> and id = <%= current_student.id %></div>
        <th>Name</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.email %></td>
          <% student.students_posts.each do |studentPost| %>
            <td><%= studentPost.post.title %></td>
          <% end %>
          <td><%= link_to 'Show', student_student_path(id: student.id) %></td>
          <td><%= link_to 'Edit', edit_student_student_path(id: student.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

app/views/student/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: [:student, @student] %>

<%= link_to 'Back', @student_student %>

app/views/student/students/show.html.erb
<p id="notice"><%= notice %></p>



<%= render 'layouts/title', :title => "Profile" %>
<%= stylesheet_link_tag 'profile' %>
<!-- <div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"> Profile </h3>
  </div> -->
  <!-- <div class="panel-body"> -->
<div class="col-md-8" style="padding-top:20px">
  <div class="toppad" >


            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title"><%= @student.name %></h3>
              </div>
              <div class="panel-body">
                <div class="row">

                  <div class="col-md-3 col-lg-3 " align="center">
                     <img alt="User Pic" src="<%= @student.avatar.url %>" class="img-circle img-responsive">
                     <%= rating_for @student, "score", imdb_avg: true, readonly: true %>
                     <%= rating_for @student, "score", readonly: true %>

                   </div>
                  <div class=" col-md-9 col-lg-9 ">
                    <table class="table table-user-information">
                      <tbody>
                        <tr>
                          <td>Age:</td>
                          <td><%= @student.age %></td>
                        </tr>
                        <tr>
                          <td>Occupation:</td>
                          <td><%= @student.occupation %></td>
                        </tr>
                        <tr>
                          <td>Department:</td>
                          <td>Programming</td>
                        </tr>
                        <tr>
                          <td>Hire date:</td>
                          <td>06/23/2013</td>
                        </tr>
                        <tr>
                          <td>Date of Birth</td>
                          <td>01/24/1988</td>
                        </tr>

                           <tr>
                               <tr>
                          <td>Gender</td>
                          <td>Female</td>
                        </tr>
                          <tr>
                          <td>Home Address</td>
                          <td>Kathmandu,Nepal</td>
                        </tr>
                        <tr>
                          <td>Email</td>
                          <td><a href="mailto:info@support.com">info@support.com</a></td>
                        </tr>
                          <td>Phone Number</td>
                          <td>123-4567-890(Landline)<br><br>555-4567-890(Mobile)
                          </td>

                        </tr>

                      </tbody>
                    </table>
                      <% @student.skills.each do |skill| %>
                        <a href="#" class="btn btn-primary"><%= skill %></a>
                      <% end %>
                  </div>
                </div>
              </div>
                   <div class="panel-footer">
                          <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                          <% if student_signed_in? %>

                            <%= link_to 'Edit', edit_student_student_path(@student), class: "btn btn-sm btn-primary" %>
                            <%= link_to 'Back', student_students_path, class: "btn btn-sm btn-primary" %>
                            <!-- <%= link_to 'all link', students_posts_path %> | -->
                          <% end %>
                          <% if !student_signed_in? %>
                            <%= link_to 'Back', :back, class: "btn btn-sm btn-primary"%>
                            <%= link_to 'add comment', new_comment_path(:view_student => @student, :current_user => current_user), class: "btn btn-sm btn-primary" %>
                            <!-- </div> -->

                            <% end %>
                          <span class="pull-right">
                              <a href="<% edit_student_student_path(@student) %>" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                              <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                          </span>
                      </div>

            </div>
          </div>
        </div>

      </div>

  </div>

app/views/student/students/status.html.erb
<p id="notice"><%= notice %></p>

<%= render 'layouts/title', :title => "Post Status" %>
<div class="col-md-12" style="padding-top:20px">
  <tbody>
    <% if @student.students_posts.empty? %>
      <p> You have not create any post. Click the button to create one ! </p>
    <% else %>

    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th> ID </th>
            <th>Title</th>
            <th>Email</th>
            <th>Post Status</th>
            <th>Status</th>
            <!-- <th>Company Profile</th> -->
            <th>button</th>
            <th>select</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <tbody>
              <% @student.students_posts.each do |students_post| %>
                <tr>
                  <td><%= students_post.id %></td>
                  <td><%= students_post.post.title %></td>
                  <td><%= link_to students_post.post.company.email, student_path(:id => students_post.post.company.id) %></td>
                  <!-- <td><%= students_post.post.company.email %></td> -->
                  <td><%= students_post.post.state %></td>
                  <td><%= students_post.status %></td>
                  <!-- <td><%= link_to 'Profile', student_path(students_post.post.company.id),  :class => "btn btn-warning "%> </td> -->
                  <% if students_post.offered_internship? %>
                      <!-- <td><%= link_to 'offer job',:class => "btn btn-primary" %>  </td>

                      <%= form_tag(choose_path(:id => students_post.id),{:action => 'choose', method: 'put'} ) do %>

                      <td><%= select_tag "whatever" ,options_for_select([ "Please Select","Accept", "Reject" ], "Please Select"),:onchange => "this.form.submit();"%></td>
                      <% end %> -->
                      <td>
                        <%= link_to choose_path(:id => students_post.id, :whatever => "Accept"), :method => :put, :class => "btn btn-default" do %>
                          <i class="fa fa-check fa-lg" style="color:green"></i>
                        <% end %>
                        <%= link_to choose_path(:id => students_post.id, :whatever => "Reject"), :method => :put, :class => "btn btn-default" do %>
                          <i class="fa fa-times fa-lg" style="color:red"></i>
                        <% end %>
                      </td>
                  <% else %>
                    <td>
                      <%=link_to students_post_path(students_post.id), :method => :delete, :class => "btn btn-default", data: {confirm: "Are you sure?"} do %>
                        <i class="fa fa-trash fa-lg" ></i>
                      <% end %>
                    </td>
                    <td></td>
                  <% end %>
                </tr>
              <% end %>
          </tbody>
        </table>
      </dev>
      <!-- <% @student.students_posts.each do |students_post| %>
        <%= render 'statusRow', {:post => students_post.post, :status => students_post.status} %>
      <% end %> -->






      <div class="small-6 columns">
        <%= submit_tag "Confirm", :type => 'submit', :class => 'btn btn-primary', :form => 'internship_select', :value => 'Confirm', method: 'put' %>
      </div>





    <% end %>
</div>